import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import '../../theme/app_colors.dart';
import '../shared/widgets/status_badge.dart';

class DhoReports extends StatelessWidget {
  const DhoReports({super.key});

  final List<Map<String, String>> _reports = const [
    {'name': 'Blantyre District Summary — March 2026', 'type': 'District Summary', 'date': '2026-03-25', 'format': 'PDF', 'status': 'Ready'},
    {'name': 'IVR Usage — Blantyre Q1 2026', 'type': 'IVR Report', 'date': '2026-03-20', 'format': 'CSV', 'status': 'Ready'},
    {'name': 'High-Risk Cases — Blantyre Feb 2026', 'type': 'Risk Report', 'date': '2026-02-28', 'format': 'PDF', 'status': 'Ready'},
    {'name': 'Task Performance — Blantyre Jan 2026', 'type': 'Task Report', 'date': '2026-01-31', 'format': 'PDF', 'status': 'Archived'},
  ];

  @override
  Widget build(BuildContext context) {
    return SingleChildScrollView(
      padding: const EdgeInsets.all(28),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            children: [
              Text('Reports',
                  style: GoogleFonts.publicSans(
                      fontSize: 22,
                      fontWeight: FontWeight.w700,
                      color: AppColors.headings)),
              const SizedBox(width: 12),
              Container(
                padding:
                    const EdgeInsets.symmetric(horizontal: 10, vertical: 4),
                decoration: BoxDecoration(
                  color: AppColors.warningBg,
                  borderRadius: BorderRadius.circular(20),
                ),
                child: Text('View & Download Only',
                    style: GoogleFonts.inter(
                        fontSize: 11,
                        fontWeight: FontWeight.w500,
                        color: AppColors.warningText)),
              ),
            ],
          ),
          const SizedBox(height: 6),
          Text('Pre-generated reports for Blantyre District',
              style: GoogleFonts.inter(fontSize: 13, color: AppColors.mutedText)),
          const SizedBox(height: 24),

          // Info banner
          Container(
            padding: const EdgeInsets.all(16),
            decoration: BoxDecoration(
              color: AppColors.infoBg,
              borderRadius: BorderRadius.circular(12),
            ),
            child: Row(
              children: [
                const Icon(Icons.info_outline_rounded,
                    size: 18, color: AppColors.infoText),
                const SizedBox(width: 12),
                Expanded(
                  child: Text(
                    'Reports are generated by the System Admin. You can view and download reports assigned to your district.',
                    style: GoogleFonts.inter(
                        fontSize: 13, color: AppColors.infoText),
                  ),
                ),
              ],
            ),
          ),
          const SizedBox(height: 24),

          // Reports list
          Container(
            padding: const EdgeInsets.all(24),
            decoration: BoxDecoration(
              color: AppColors.surfaceContainerLowest,
              borderRadius: BorderRadius.circular(16),
              boxShadow: const [
                BoxShadow(
                    color: AppColors.shadowColor,
                    blurRadius: 24,
                    offset: Offset(0, 4))
              ],
            ),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text('Available Reports',
                    style: GoogleFonts.publicSans(
                        fontSize: 16,
                        fontWeight: FontWeight.w600,
                        color: AppColors.headings)),
                const SizedBox(height: 16),
                ..._reports.map((r) => _ReportRow(report: r)),
              ],
            ),
          ),
        ],
      ),
    );
  }
}

class _ReportRow extends StatelessWidget {
  final Map<String, String> report;
  const _ReportRow({required this.report});

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 16),
      child: Row(
        children: [
          Container(
            padding: const EdgeInsets.all(10),
            decoration: BoxDecoration(
              color: AppColors.infoBg,
              borderRadius: BorderRadius.circular(10),
            ),
            child: Icon(
              report['format'] == 'CSV'
                  ? Icons.table_chart_rounded
                  : Icons.picture_as_pdf_rounded,
              size: 20,
              color: AppColors.primary,
            ),
          ),
          const SizedBox(width: 14),
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(report['name']!,
                    style: GoogleFonts.inter(
                        fontSize: 13,
                        fontWeight: FontWeight.w500,
                        color: AppColors.onSurface)),
                Text('${report['type']} · ${report['date']}',
                    style: GoogleFonts.inter(
                        fontSize: 11, color: AppColors.mutedText)),
              ],
            ),
          ),
          StatusBadge(
            label: report['format']!,
            type: BadgeType.info,
          ),
          const SizedBox(width: 12),
          StatusBadge(
            label: report['status']!,
            type: report['status'] == 'Ready'
                ? BadgeType.success
                : BadgeType.neutral,
          ),
          const SizedBox(width: 12),
          ElevatedButton.icon(
            onPressed: () {},
            icon: const Icon(Icons.download_rounded, size: 16),
            label: Text('Download',
                style: GoogleFonts.inter(
                    fontSize: 12, fontWeight: FontWeight.w500)),
            style: ElevatedButton.styleFrom(
              backgroundColor: AppColors.primary,
              foregroundColor: Colors.white,
              shape: RoundedRectangleBorder(
                  borderRadius: BorderRadius.circular(8)),
              padding:
                  const EdgeInsets.symmetric(horizontal: 14, vertical: 10),
              elevation: 0,
            ),
          ),
        ],
      ),
    );
  }
}
